site_name: vinsmoke-three - 機械学習・深層学習ドキュメント
site_url: https://vinsmoke-three.com
site_description: PyTorch、機械学習、深層学習の実践的なチュートリアルとコード例を日本語で提供する技術ドキュメントサイト
site_author: vinsmoke-three
repo_url: https://github.com/vinsmoke-three/vinsmoke-three-docs
repo_name: vinsmoke-three/vinsmoke-three-docs
theme:
  name: material
  language: ja
  icon:
    logo: material/library-outline
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
      - scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: black
        accent: indigo
        toggle:
          icon: material/brightness-4
          name: Switch to system preference

plugins:
  - search:
      lang: ja
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: datetime
      timezone: Asia/Tokyo
      locale: ja

# Copyright
copyright: Copyright &copy; 2025 - 2025 vinsmoke-three

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      title: 目次

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vinsmoke-three
      name: GitHub
  tags:
    PyTorch: pytorch
    機械学習: machine-learning
    深層学習: deep-learning
    カスタムデータセット: custom-datasets
    画像分類: image-classification
    コンピュータビジョン: computer-vision
    データ拡張: data-augmentation
    テンソル: tensor
    初心者向け: beginner
    中級者向け: intermediate
    上級者向け: advanced
    線形回帰: linear-regression
    ワークフロー: workflow
    分類: classification
    ニューラルネットワーク: neural-network
    CNN: convolutional-neural-network
    TinyVGG: tinyvgg
    モジュール化: modularization
    スクリプトモード: script-mode
    再利用: reusability
    MLパイプライン: ml-pipeline
    チュートリアル: tutorial
    実践: practical
    Python: python
    FashionMNIST: fashion-mnist
  
# Page tree
nav:
  - Home: index.md
  - PyTorch:
    - 0. setup: PyTorch/00_setup.md
    - 1. PyTorch fundamentals: PyTorch/01_pytorch_fundamentals.md
    - 2. PyTorch workflow: PyTorch/02_pytorch_workflow.md
    - 3. PyTorch classification: PyTorch/03_pytorch_classification.md
    - 4. PyTorch computer vision: PyTorch/04_pytorch_computer_vision.md
    - 5. PyTorch custom datasets: PyTorch/05_pytorch_custom_datasets.md
    - 6. PyTorch modular: PyTorch/06_pytorch_modular.md